export interface LanguageProfile {
  id: string;
  name: string;
  icon: string;
  extensions: string[];
  configFiles: string[];
  install: string[];
  build: string[];
  outputDirs: string[];
  startCommand: (port: number, deployDir: string) => { cmd: string; args: string[]; cwd?: string };
  env?: Record<string, string>;
  port?: number;
  detectPriority?: number;
}

export const LANGUAGES: LanguageProfile[] = [
  // ═══════════════════════════════════════════════════════════════
  // JavaScript / TypeScript
  // ═══════════════════════════════════════════════════════════════
  {
    id: "nextjs",
    name: "Next.js",
    icon: "▲",
    extensions: [".tsx", ".ts", ".jsx", ".js"],
    configFiles: ["next.config.js", "next.config.mjs", "next.config.ts", "next.config.cjs"],
    install: ["npm install"],
    build: ["npx next build"],
    outputDirs: [".next/standalone", ".next"],
    startCommand: (port) => ({ cmd: "node", args: [".next/standalone/server.js"], cwd: ".next/standalone" }),
    env: { PORT: "3000", NODE_ENV: "production" },
    detectPriority: 100,
  },
  {
    id: "nextjs-static",
    name: "Next.js (Static Export)",
    icon: "▲",
    extensions: [".tsx", ".ts", ".jsx", ".js"],
    configFiles: ["next.config.js", "next.config.mjs", "next.config.ts"],
    install: ["npm install"],
    build: ["npx next build"],
    outputDirs: ["out"],
    startCommand: () => ({ cmd: "npx", args: ["serve", "out", "-l", "3000"] }),
    detectPriority: 99,
  },
  {
    id: "react-vite",
    name: "React (Vite)",
    icon: "⚡",
    extensions: [".tsx", ".ts", ".jsx", ".js", ".vue", ".svelte"],
    configFiles: ["vite.config.js", "vite.config.ts", "vite.config.mjs", "vite.config.cjs"],
    install: ["npm install"],
    build: ["npm run build"],
    outputDirs: ["dist"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", "dist", "-l", String(port)] }),
    detectPriority: 95,
  },
  {
    id: "vue",
    name: "Vue.js",
    icon: "💚",
    extensions: [".vue", ".ts", ".js"],
    configFiles: ["vue.config.js", "vue.config.ts", "nuxt.config.js", "nuxt.config.ts", "nuxt.config.mjs"],
    install: ["npm install"],
    build: ["npm run build"],
    outputDirs: ["dist", "dist/ssr", ".output"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", "dist", "-l", String(port)] }),
    detectPriority: 90,
  },
  {
    id: "nuxt",
    name: "Nuxt",
    icon: "💚",
    extensions: [".vue", ".ts", ".js"],
    configFiles: ["nuxt.config.js", "nuxt.config.ts", "nuxt.config.mjs"],
    install: ["npm install"],
    build: ["npx nuxi build"],
    outputDirs: [".output/server", ".output/public", ".nuxt"],
    startCommand: (port) => ({ cmd: "node", args: [".output/server/index.mjs"] }),
    env: { PORT: "3000", NITRO_PORT: "3000" },
    detectPriority: 101,
  },
  {
    id: "sveltekit",
    name: "SvelteKit",
    icon: "🔥",
    extensions: [".svelte", ".ts", ".js"],
    configFiles: ["svelte.config.js", "svelte.config.ts", "svelte.config.mjs"],
    install: ["npm install"],
    build: ["npm run build"],
    outputDirs: ["build"],
    startCommand: (port) => ({ cmd: "node", args: ["build/index.js"] }),
    env: { PORT: "3000" },
    detectPriority: 100,
  },
  {
    id: "remix",
    name: "Remix",
    icon: "💿",
    extensions: [".tsx", ".ts", ".jsx", ".js"],
    configFiles: ["remix.config.js", "remix.config.ts", "remix.config.mjs"],
    install: ["npm install"],
    build: ["npx remix build"],
    outputDirs: ["build", "public/build"],
    startCommand: (port) => ({ cmd: "node", args: ["build/server/index.js"] }),
    env: { PORT: "3000" },
    detectPriority: 98,
  },
  {
    id: "astro",
    name: "Astro",
    icon: "🚀",
    extensions: [".astro", ".ts", ".tsx", ".js", ".jsx"],
    configFiles: ["astro.config.mjs", "astro.config.js", "astro.config.ts"],
    install: ["npm install"],
    build: ["npx astro build"],
    outputDirs: ["dist"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", "dist", "-l", String(port)] }),
    detectPriority: 97,
  },
  {
    id: "gatsby",
    name: "Gatsby",
    icon: "🟣",
    extensions: [".tsx", ".ts", ".jsx", ".js"],
    configFiles: ["gatsby-config.js", "gatsby-config.ts", "gatsby-node.js"],
    install: ["npm install"],
    build: ["npx gatsby build"],
    outputDirs: ["public"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", "public", "-l", String(port)] }),
    detectPriority: 96,
  },
  {
    id: "angular",
    name: "Angular",
    icon: "🅰️",
    extensions: [".ts", ".html", ".scss", ".css"],
    configFiles: ["angular.json", "angular-cli.json"],
    install: ["npm install"],
    build: ["npx ng build"],
    outputDirs: ["dist"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", "dist", "-l", String(port)] }),
    detectPriority: 94,
  },
  {
    id: "ember",
    name: "Ember.js",
    icon: "🟠",
    extensions: [".js", ".ts", ".hbs"],
    configFiles: ["ember-cli-build.js"],
    install: ["npm install"],
    build: ["npx ember build"],
    outputDirs: ["dist"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", "dist", "-l", String(port)] }),
    detectPriority: 85,
  },
  {
    id: "solidjs",
    name: "SolidJS",
    icon: "💙",
    extensions: [".tsx", ".ts", ".jsx", ".js"],
    configFiles: ["vite.config.ts", "vite.config.js", "solid.config.js", "solid.config.ts"],
    install: ["npm install"],
    build: ["npm run build"],
    outputDirs: ["dist"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", "dist", "-l", String(port)] }),
    detectPriority: 88,
  },
  {
    id: "qwik",
    name: "Qwik",
    icon: "⚡",
    extensions: [".tsx", ".ts", ".jsx", ".js"],
    configFiles: ["vite.config.ts", "vite.config.js", "qwik.config.ts", "qwik.config.js"],
    install: ["npm install"],
    build: ["npm run build"],
    outputDirs: ["dist"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", "dist", "-l", String(port)] }),
    detectPriority: 87,
  },
  {
    id: "remix-vite",
    name: "Remix (Vite)",
    icon: "💿",
    extensions: [".tsx", ".ts", ".jsx", ".js"],
    configFiles: ["vite.config.ts", "vite.config.js"],
    install: ["npm install"],
    build: ["npx remix vite:build"],
    outputDirs: ["build/server", "build/client"],
    startCommand: (port) => ({ cmd: "node", args: ["build/server/index.js"] }),
    env: { PORT: "3000" },
    detectPriority: 99,
  },
  {
    id: "hexo",
    name: "Hexo",
    icon: "📝",
    extensions: [".ejs", ".pug", ".md", ".yml"],
    configFiles: ["_config.yml", "package.json"],
    install: ["npm install"],
    build: ["npx hexo generate"],
    outputDirs: ["public"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", "public", "-l", String(port)] }),
    detectPriority: 60,
  },
  {
    id: "hugo",
    name: "Hugo",
    icon: "📄",
    extensions: [".html", ".md", ".toml"],
    configFiles: ["config.toml", "config.yaml", "hugo.toml", "hugo.yaml"],
    install: [],
    build: ["hugo --minify"],
    outputDirs: ["public"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", "public", "-l", String(port)] }),
    detectPriority: 70,
  },
  {
    id: "jekyll",
    name: "Jekyll",
    icon: "💎",
    extensions: [".html", ".md", ".rb", ".liquid"],
    configFiles: ["_config.yml", "Gemfile"],
    install: ["bundle install"],
    build: ["bundle exec jekyll build"],
    outputDirs: ["_site"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", "_site", "-l", String(port)] }),
    detectPriority: 65,
  },
  {
    id: "docusaurus",
    name: "Docusaurus",
    icon: "🐕",
    extensions: [".tsx", ".ts", ".jsx", ".js", ".md", ".mdx"],
    configFiles: ["docusaurus.config.js", "docusaurus.config.ts"],
    install: ["npm install"],
    build: ["npx docusaurus build"],
    outputDirs: ["build"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", "build", "-l", String(port)] }),
    detectPriority: 75,
  },
  {
    id: "vitepress",
    name: "VitePress",
    icon: "📝",
    extensions: [".vue", ".md", ".ts", ".js"],
    configFiles: ["docs/.vitepress/config.js", "docs/.vitepress/config.ts", ".vitepress/config.js"],
    install: ["npm install"],
    build: ["npx vitepress build"],
    outputDirs: [".vitepress/dist"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", ".vitepress/dist", "-l", String(port)] }),
    detectPriority: 68,
  },

  // ═══════════════════════════════════════════════════════════════
  // Node.js / Express / Backend
  // ═══════════════════════════════════════════════════════════════
  {
    id: "express",
    name: "Express.js",
    icon: "🚂",
    extensions: [".js", ".ts", ".mjs", ".cjs"],
    configFiles: ["package.json"],
    install: ["npm install"],
    build: [],
    outputDirs: ["."],
    startCommand: (port) => ({ cmd: "node", args: ["src/index.js"] }),
    env: { PORT: "3000" },
    detectPriority: 50,
  },
  {
    id: "fastify",
    name: "Fastify",
    icon: "⚡",
    extensions: [".js", ".ts", ".mjs"],
    configFiles: ["package.json"],
    install: ["npm install"],
    build: [],
    outputDirs: ["."],
    startCommand: (port) => ({ cmd: "node", args: ["src/index.js"] }),
    env: { PORT: "3000" },
    detectPriority: 51,
  },
  {
    id: "nestjs",
    name: "NestJS",
    icon: "🐱",
    extensions: [".ts", ".js"],
    configFiles: ["nest-cli.json", "nest-cli.js"],
    install: ["npm install"],
    build: ["npx nest build"],
    outputDirs: ["dist"],
    startCommand: (port) => ({ cmd: "node", args: ["dist/main.js"] }),
    env: { PORT: "3000" },
    detectPriority: 80,
  },
  {
    id: "adonisjs",
    name: "AdonisJS",
    icon: "🔺",
    extensions: [".ts", ".js"],
    configFiles: ["adonisrc.ts", "adonisrc.js"],
    install: ["npm install"],
    build: ["node ace build --production"],
    outputDirs: ["build"],
    startCommand: (port) => ({ cmd: "node", args: ["build/server.js"] }),
    env: { PORT: "3000", NODE_ENV: "production" },
    detectPriority: 78,
  },
  {
    id: "hono",
    name: "Hono",
    icon: "🔥",
    extensions: [".ts", ".js", ".tsx"],
    configFiles: ["package.json"],
    install: ["npm install"],
    build: [],
    outputDirs: ["."],
    startCommand: (port) => ({ cmd: "node", args: ["src/index.js"] }),
    env: { PORT: "3000" },
    detectPriority: 52,
  },
  {
    id: "nitro",
    name: "Nitro",
    icon: "⚡",
    extensions: [".ts", ".js"],
    configFiles: ["nitro.config.ts", "nitro.config.js"],
    install: ["npm install"],
    build: ["npx nitro build"],
    outputDirs: [".output/server"],
    startCommand: (port) => ({ cmd: "node", args: [".output/server/index.mjs"] }),
    env: { PORT: "3000", NITRO_PORT: "3000" },
    detectPriority: 82,
  },
  {
    id: "elysia",
    name: "ElysiaJS (Bun)",
    icon: "🍞",
    extensions: [".ts", ".js"],
    configFiles: ["package.json"],
    install: ["bun install"],
    build: ["bun build --production src/index.ts --outdir dist"],
    outputDirs: ["dist"],
    startCommand: (port) => ({ cmd: "bun", args: ["dist/index.js"] }),
    env: { PORT: "3000" },
    detectPriority: 53,
  },
  {
    id: "lynx",
    name: "Lynx (Deno)",
    icon: "🦕",
    extensions: [".ts", ".js"],
    configFiles: ["deno.json", "deno.jsonc", "deno.lock"],
    install: [],
    build: [],
    outputDirs: ["."],
    startCommand: (port) => ({ cmd: "deno", args: ["run", "--allow-net", "--allow-env", "main.ts"] }),
    env: { PORT: "3000" },
    detectPriority: 54,
  },

  // ═══════════════════════════════════════════════════════════════
  // Python
  // ═══════════════════════════════════════════════════════════════
  {
    id: "django",
    name: "Django",
    icon: "🎸",
    extensions: [".py", ".html", ".css", ".js"],
    configFiles: ["manage.py", "settings.py", "pyproject.toml"],
    install: ["pip install -r requirements.txt"],
    build: ["python manage.py collectstatic --noinput"],
    outputDirs: ["staticfiles", "static"],
    startCommand: (port) => ({ cmd: "python", args: ["manage.py", "runserver", "0.0.0.0:3000"] }),
    env: { DJANGO_SETTINGS_MODULE: "settings", PYTHONUNBUFFERED: "1" },
    detectPriority: 80,
  },
  {
    id: "flask",
    name: "Flask",
    icon: "🧪",
    extensions: [".py", ".html", ".css"],
    configFiles: ["app.py", "wsgi.py", "requirements.txt", "pyproject.toml"],
    install: ["pip install -r requirements.txt"],
    build: [],
    outputDirs: ["."],
    startCommand: (port) => ({ cmd: "python", args: ["app.py"] }),
    env: { FLASK_APP: "app.py", FLASK_ENV: "production", PYTHONUNBUFFERED: "1" },
    detectPriority: 70,
  },
  {
    id: "fastapi",
    name: "FastAPI",
    icon: "⚡",
    extensions: [".py"],
    configFiles: ["main.py", "app.py", "requirements.txt", "pyproject.toml"],
    install: ["pip install -r requirements.txt"],
    build: [],
    outputDirs: ["."],
    startCommand: (port) => ({ cmd: "uvicorn", args: ["main:app", "--host", "0.0.0.0", "--port", "3000"] }),
    env: { PYTHONUNBUFFERED: "1" },
    detectPriority: 75,
  },
  {
    id: "starlette",
    name: "Starlette",
    icon: "⭐",
    extensions: [".py"],
    configFiles: ["main.py", "app.py", "requirements.txt"],
    install: ["pip install -r requirements.txt"],
    build: [],
    outputDirs: ["."],
    startCommand: (port) => ({ cmd: "uvicorn", args: ["main:app", "--host", "0.0.0.0", "--port", "3000"] }),
    env: { PYTHONUNBUFFERED: "1" },
    detectPriority: 60,
  },
  {
    id: "sanic",
    name: "Sanic",
    icon: "🧪",
    extensions: [".py"],
    configFiles: ["app.py", "requirements.txt"],
    install: ["pip install -r requirements.txt"],
    build: [],
    outputDirs: ["."],
    startCommand: (port) => ({ cmd: "python", args: ["app.py"] }),
    env: { SANIC_HOST: "0.0.0.0", SANIC_PORT: "3000", PYTHONUNBUFFERED: "1" },
    detectPriority: 55,
  },
  {
    id: "bottle",
    name: "Bottle",
    icon: "🍶",
    extensions: [".py"],
    configFiles: ["app.py", "requirements.txt"],
    install: ["pip install -r requirements.txt"],
    build: [],
    outputDirs: ["."],
    startCommand: (port) => ({ cmd: "python", args: ["app.py"] }),
    env: { PYTHONUNBUFFERED: "1" },
    detectPriority: 40,
  },
  {
    id: "quart",
    name: "Quart",
    icon: "🧪",
    extensions: [".py"],
    configFiles: ["app.py", "requirements.txt"],
    install: ["pip install -r requirements.txt"],
    build: [],
    outputDirs: ["."],
    startCommand: (port) => ({ cmd: "python", args: ["app.py"] }),
    env: { PYTHONUNBUFFERED: "1" },
    detectPriority: 45,
  },
  {
    id: "tornado",
    name: "Tornado",
    icon: "🌪️",
    extensions: [".py"],
    configFiles: ["app.py", "requirements.txt"],
    install: ["pip install -r requirements.txt"],
    build: [],
    outputDirs: ["."],
    startCommand: (port) => ({ cmd: "python", args: ["app.py"] }),
    env: { PYTHONUNBUFFERED: "1" },
    detectPriority: 42,
  },
  {
    id: "gunicorn",
    name: "Gunicorn",
    icon: "🦄",
    extensions: [".py"],
    configFiles: ["gunicorn.conf.py", "requirements.txt", "Procfile"],
    install: ["pip install -r requirements.txt"],
    build: [],
    outputDirs: ["."],
    startCommand: (port) => ({ cmd: "gunicorn", args: ["app:app", "--bind", "0.0.0.0:3000", "--workers", "4"] }),
    env: { PYTHONUNBUFFERED: "1" },
    detectPriority: 65,
  },
  {
    id: "static-python",
    name: "Python (Static)",
    icon: "🐍",
    extensions: [".py"],
    configFiles: ["requirements.txt", "pyproject.toml"],
    install: ["pip install -r requirements.txt"],
    build: ["python -m build"],
    outputDirs: ["dist", "build"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", "dist", "-l", String(port)] }),
    detectPriority: 30,
  },

  // ═══════════════════════════════════════════════════════════════
  // Go
  // ═══════════════════════════════════════════════════════════════
  {
    id: "go",
    name: "Go",
    icon: "🐹",
    extensions: [".go"],
    configFiles: ["go.mod", "go.sum", "main.go"],
    install: ["go mod download"],
    build: ["go build -o server ."],
    outputDirs: ["."],
    startCommand: () => ({ cmd: "./server", args: [] }),
    env: { PORT: "3000", GOPATH: "/root/go" },
    detectPriority: 70,
  },
  {
    id: "echo",
    name: "Go (Echo)",
    icon: "🔊",
    extensions: [".go"],
    configFiles: ["go.mod", "main.go"],
    install: ["go mod download"],
    build: ["go build -o server ."],
    outputDirs: ["."],
    startCommand: () => ({ cmd: "./server", args: [] }),
    env: { PORT: "3000" },
    detectPriority: 65,
  },
  {
    id: "gin",
    name: "Go (Gin)",
    icon: "🍸",
    extensions: [".go"],
    configFiles: ["go.mod", "main.go"],
    install: ["go mod download"],
    build: ["go build -o server ."],
    outputDirs: ["."],
    startCommand: () => ({ cmd: "./server", args: [] }),
    env: { PORT: "3000" },
    detectPriority: 66,
  },
  {
    id: "fiber",
    name: "Go (Fiber)",
    icon: "🧶",
    extensions: [".go"],
    configFiles: ["go.mod", "main.go"],
    install: ["go mod download"],
    build: ["go build -o server ."],
    outputDirs: ["."],
    startCommand: () => ({ cmd: "./server", args: [] }),
    env: { PORT: "3000" },
    detectPriority: 67,
  },
  {
    id: "hugo-go",
    name: "Hugo (Go)",
    icon: "📄",
    extensions: [".html", ".md", ".toml"],
    configFiles: ["config.toml", "hugo.toml"],
    install: [],
    build: ["hugo --minify"],
    outputDirs: ["public"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", "public", "-l", String(port)] }),
    detectPriority: 71,
  },

  // ═══════════════════════════════════════════════════════════════
  // Rust
  // ═══════════════════════════════════════════════════════════════
  {
    id: "rust",
    name: "Rust",
    icon: "🦀",
    extensions: [".rs"],
    configFiles: ["Cargo.toml", "Cargo.lock"],
    install: [],
    build: ["cargo build --release"],
    outputDirs: ["target/release"],
    startCommand: () => ({ cmd: "./target/release/server", args: [] }),
    env: { PORT: "3000" },
    detectPriority: 70,
  },
  {
    id: "actix",
    name: "Rust (Actix)",
    icon: "⚡",
    extensions: [".rs"],
    configFiles: ["Cargo.toml"],
    install: [],
    build: ["cargo build --release"],
    outputDirs: ["target/release"],
    startCommand: () => ({ cmd: "./target/release/server", args: [] }),
    env: { PORT: "3000", RUST_LOG: "info" },
    detectPriority: 68,
  },
  {
    id: "axum",
    name: "Rust (Axum)",
    icon: "🗼",
    extensions: [".rs"],
    configFiles: ["Cargo.toml"],
    install: [],
    build: ["cargo build --release"],
    outputDirs: ["target/release"],
    startCommand: () => ({ cmd: "./target/release/server", args: [] }),
    env: { PORT: "3000", RUST_LOG: "info" },
    detectPriority: 69,
  },
  {
    id: "rocket",
    name: "Rust (Rocket)",
    icon: "🚀",
    extensions: [".rs"],
    configFiles: ["Cargo.toml", "Rocket.toml"],
    install: [],
    build: ["cargo build --release"],
    outputDirs: ["target/release"],
    startCommand: () => ({ cmd: "./target/release/server", args: [] }),
    env: { PORT: "3000" },
    detectPriority: 66,
  },
  {
    id: "warp",
    name: "Rust (Warp)",
    icon: "🌀",
    extensions: [".rs"],
    configFiles: ["Cargo.toml"],
    install: [],
    build: ["cargo build --release"],
    outputDirs: ["target/release"],
    startCommand: () => ({ cmd: "./target/release/server", args: [] }),
    env: { PORT: "3000" },
    detectPriority: 65,
  },
  {
    id: "leptos",
    name: "Rust (Leptos)",
    icon: "🦟",
    extensions: [".rs", ".html"],
    configFiles: ["Cargo.toml", "Leptos.toml"],
    install: [],
    build: ["cargo leptos build --release"],
    outputDirs: ["target/release", "target/site"],
    startCommand: () => ({ cmd: "./target/release/server", args: [] }),
    env: { PORT: "3000" },
    detectPriority: 72,
  },
  {
    id: "dioxus",
    name: "Rust (Dioxus)",
    icon: "🎯",
    extensions: [".rs"],
    configFiles: ["Cargo.toml", "Dioxus.toml"],
    install: [],
    build: ["dx build --release"],
    outputDirs: ["dist"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", "dist", "-l", String(port)] }),
    detectPriority: 71,
  },

  // ═══════════════════════════════════════════════════════════════
  // Ruby
  // ═══════════════════════════════════════════════════════════════
  {
    id: "rails",
    name: "Ruby on Rails",
    icon: "💎",
    extensions: [".rb", ".erb", ".html", ".haml"],
    configFiles: ["Gemfile", "Rakefile", "config/routes.rb"],
    install: ["bundle install"],
    build: ["bundle exec rake assets:precompile"],
    outputDirs: ["public/assets"],
    startCommand: (port) => ({ cmd: "bundle", args: ["exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000", "-e", "production"] }),
    env: { RAILS_ENV: "production", RAILS_LOG_TO_STDOUT: "1" },
    detectPriority: 80,
  },
  {
    id: "sinatra",
    name: "Sinatra",
    icon: "🎵",
    extensions: [".rb"],
    configFiles: ["Gemfile", "app.rb", "config.ru"],
    install: ["bundle install"],
    build: [],
    outputDirs: ["."],
    startCommand: (port) => ({ cmd: "bundle", args: ["exec", "ruby", "app.rb", "-p", "3000"] }),
    env: { RACK_ENV: "production" },
    detectPriority: 55,
  },
  {
    id: "hanami",
    name: "Hanami",
    icon: "🌸",
    extensions: [".rb"],
    configFiles: ["Gemfile", "hanami.rb"],
    install: ["bundle install"],
    build: ["bundle exec hanami build"],
    outputDirs: ["public"],
    startCommand: (port) => ({ cmd: "bundle", args: ["exec", "hanami", "server", "-p", "3000"] }),
    env: { HANAMI_ENV: "production" },
    detectPriority: 58,
  },
  {
    id: "ruby-static",
    name: "Ruby (Static)",
    icon: "💎",
    extensions: [".rb"],
    configFiles: ["Gemfile"],
    install: ["bundle install"],
    build: [],
    outputDirs: ["."],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", ".", "-l", String(port)] }),
    detectPriority: 25,
  },

  // ═══════════════════════════════════════════════════════════════
  // PHP
  // ═══════════════════════════════════════════════════════════════
  {
    id: "laravel",
    name: "Laravel",
    icon: "🔴",
    extensions: [".php", ".blade.php"],
    configFiles: ["composer.json", "artisan", "config/app.php"],
    install: ["composer install --no-dev --optimize-autoloader"],
    build: ["php artisan config:cache", "php artisan route:cache", "php artisan view:cache"],
    outputDirs: ["public", "storage"],
    startCommand: (port) => ({ cmd: "php", args: ["artisan", "serve", "--host=0.0.0.0", "--port=3000"] }),
    env: { APP_ENV: "production", APP_DEBUG: "false" },
    detectPriority: 85,
  },
  {
    id: "symfony",
    name: "Symfony",
    icon: " symfony",
    extensions: [".php", ".twig"],
    configFiles: ["composer.json", "symfony.lock", "config/bundles.php"],
    install: ["composer install --no-dev --optimize-autoloader"],
    build: ["php bin/console cache:clear", "php bin/console assets:install public"],
    outputDirs: ["public", "var"],
    startCommand: (port) => ({ cmd: "php", args: ["-S", "0.0.0.0:3000", "-t", "public"] }),
    env: { APP_ENV: "production", APP_DEBUG: "0" },
    detectPriority: 80,
  },
  {
    id: "wordpress",
    name: "WordPress",
    icon: "📝",
    extensions: [".php", ".html"],
    configFiles: ["wp-config.php", "wp-load.php"],
    install: [],
    build: [],
    outputDirs: ["."],
    startCommand: (port) => ({ cmd: "php", args: ["-S", "0.0.0.0:3000"] }),
    env: { WORDPRESS_DB_HOST: "localhost" },
    detectPriority: 60,
  },
  {
    id: "static-php",
    name: "PHP (Static)",
    icon: "🐘",
    extensions: [".php"],
    configFiles: ["composer.json"],
    install: ["composer install --no-dev"],
    build: [],
    outputDirs: ["public"],
    startCommand: (port) => ({ cmd: "php", args: ["-S", "0.0.0.0:3000", "-t", "public"] }),
    detectPriority: 35,
  },

  // ═══════════════════════════════════════════════════════════════
  // Java / Kotlin / Scala
  // ═══════════════════════════════════════════════════════════════
  {
    id: "spring-boot",
    name: "Spring Boot",
    icon: "🍃",
    extensions: [".java", ".kt", ".xml", ".gradle"],
    configFiles: ["pom.xml", "build.gradle", "build.gradle.kts", "mvnw", "gradlew"],
    install: ["./mvnw dependency:resolve", "or", "./gradlew dependencies"],
    build: ["./mvnw clean package -DskipTests", "or", "./gradlew bootJar"],
    outputDirs: ["target", "build/libs"],
    startCommand: () => ({ cmd: "java", args: ["-jar", "target/*.jar"] }),
    env: { JAVA_OPTS: "-Xmx512m" },
    detectPriority: 80,
  },
  {
    id: "spring-boot-gradle",
    name: "Spring Boot (Gradle)",
    icon: "🍃",
    extensions: [".java", ".kt", ".gradle", ".gradle.kts"],
    configFiles: ["build.gradle", "build.gradle.kts", "gradlew"],
    install: ["./gradlew dependencies"],
    build: ["./gradlew bootJar"],
    outputDirs: ["build/libs"],
    startCommand: () => ({ cmd: "java", args: ["-jar", "build/libs/*.jar"] }),
    env: { JAVA_OPTS: "-Xmx512m" },
    detectPriority: 81,
  },
  {
    id: "kotlin",
    name: "Kotlin",
    icon: "🟣",
    extensions: [".kt", ".kts"],
    configFiles: ["build.gradle.kts", "pom.xml"],
    install: ["./gradlew dependencies", "or", "./mvnw dependency:resolve"],
    build: ["./gradlew build", "or", "./mvnw package"],
    outputDirs: ["build/libs", "target"],
    startCommand: () => ({ cmd: "java", args: ["-jar", "build/libs/*.jar"] }),
    env: { JAVA_OPTS: "-Xmx512m" },
    detectPriority: 65,
  },
  {
    id: "scala",
    name: "Scala",
    icon: "🔴",
    extensions: [".scala", ".sbt"],
    configFiles: ["build.sbt", "project/build.properties"],
    install: [],
    build: ["sbt package"],
    outputDirs: ["target/scala-*"],
    startCommand: () => ({ cmd: "sbt", args: ["run"] }),
    env: { JAVA_OPTS: "-Xmx512m" },
    detectPriority: 60,
  },
  {
    id: "micronaut",
    name: "Micronaut",
    icon: "🧊",
    extensions: [".java", ".kt", ".groovy"],
    configFiles: ["build.gradle", "pom.xml", "micronaut-cli.yml"],
    install: ["./gradlew dependencies", "or", "./mvnw dependency:resolve"],
    build: ["./gradlew shadowJar", "or", "./mvnw package"],
    outputDirs: ["build/libs", "target"],
    startCommand: () => ({ cmd: "java", args: ["-jar", "build/libs/*-all.jar"] }),
    env: { MICRONAUT_ENVIRONMENTS: "production" },
    detectPriority: 68,
  },
  {
    id: "quarkus",
    name: "Quarkus",
    icon: "🚀",
    extensions: [".java", ".kt"],
    configFiles: ["pom.xml", "build.gradle"],
    install: ["./mvnw dependency:resolve", "or", "./gradlew dependencies"],
    build: ["./mvnw clean package -DskipTests", "or", "./gradlew build -x test"],
    outputDirs: ["target/quarkus-app", "build/quarkus-app"],
    startCommand: () => ({ cmd: "java", args: ["-jar", "target/*-runner.jar"] }),
    env: { QUARKUS_HTTP_PORT: "3000" },
    detectPriority: 70,
  },
  {
    id: "vertx",
    name: "Vert.x",
    icon: "🔺",
    extensions: [".java", ".kt", ".groovy", ".js"],
    configFiles: ["pom.xml", "build.gradle", "vertx.json"],
    install: ["./mvnw dependency:resolve", "or", "./gradlew dependencies"],
    build: ["./mvnw package", "or", "./gradlew shadowJar"],
    outputDirs: ["target", "build/libs"],
    startCommand: () => ({ cmd: "java", args: ["-jar", "target/*.jar"] }),
    detectPriority: 55,
  },
  {
    id: "clojure",
    name: "Clojure",
    icon: "λ",
    extensions: [".clj", ".cljs", ".cljc", ".edn"],
    configFiles: ["project.clj", "deps.edn", "shadow-cljs.edn"],
    install: ["lein deps", "or", "clojure -P"],
    build: ["lein uberjar", "or", "clojure -T:build uberjar"],
    outputDirs: ["target"],
    startCommand: () => ({ cmd: "java", args: ["-jar", "target/uberjar/*.jar"] }),
    env: { LEIN_ROOT: "1" },
    detectPriority: 55,
  },

  // ═══════════════════════════════════════════════════════════════
  // C# / .NET
  // ═══════════════════════════════════════════════════════════════
  {
    id: "dotnet",
    name: "ASP.NET Core",
    icon: "🟦",
    extensions: [".cs", ".cshtml", ".razor", ".csproj"],
    configFiles: ["*.csproj", "*.sln", "Program.cs"],
    install: ["dotnet restore"],
    build: ["dotnet publish -c Release -o out"],
    outputDirs: ["out"],
    startCommand: () => ({ cmd: "dotnet", args: ["out/*.dll"] }),
    env: { ASPNETCORE_URLS: "http://0.0.0.0:3000", DOTNET_ENVIRONMENT: "Production" },
    detectPriority: 80,
  },
  {
    id: "blazor",
    name: "Blazor",
    icon: "🔵",
    extensions: [".cs", ".razor", ".cshtml"],
    configFiles: ["*.csproj", "Program.cs"],
    install: ["dotnet restore"],
    build: ["dotnet publish -c Release -o out"],
    outputDirs: ["out/wwwroot", "out"],
    startCommand: () => ({ cmd: "dotnet", args: ["out/*.dll"] }),
    env: { ASPNETCORE_URLS: "http://0.0.0.0:3000" },
    detectPriority: 75,
  },
  {
    id: "maui",
    name: ".NET MAUI",
    icon: "📱",
    extensions: [".cs", ".xaml", ".razor"],
    configFiles: ["*.csproj"],
    install: ["dotnet restore"],
    build: ["dotnet publish -c Release"],
    outputDirs: ["bin/Release"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", "bin/Release", "-l", String(port)] }),
    detectPriority: 40,
  },

  // ═══════════════════════════════════════════════════════════════
  // Elixir / Erlang
  // ═══════════════════════════════════════════════════════════════
  {
    id: "phoenix",
    name: "Phoenix (Elixir)",
    icon: "🔥",
    extensions: [".ex", ".exs", ".heex", ".leex"],
    configFiles: ["mix.exs", "mix.lock"],
    install: ["mix deps.get"],
    build: ["mix assets.deploy", "or", "mix phx.digest"],
    outputDirs: ["priv/static"],
    startCommand: () => ({ cmd: "mix", args: ["phx.server"] }),
    env: { MIX_ENV: "prod" },
    detectPriority: 75,
  },
  {
    id: "elixir",
    name: "Elixir",
    icon: "💧",
    extensions: [".ex", ".exs"],
    configFiles: ["mix.exs"],
    install: ["mix deps.get"],
    build: ["mix esbuild"],
    outputDirs: ["_build"],
    startCommand: () => ({ cmd: "mix", args: ["run", "--no-halt"] }),
    env: { MIX_ENV: "prod" },
    detectPriority: 55,
  },

  // ═══════════════════════════════════════════════════════════════
  // Dart / Flutter
  // ═══════════════════════════════════════════════════════════════
  {
    id: "flutter",
    name: "Flutter",
    icon: "💙",
    extensions: [".dart"],
    configFiles: ["pubspec.yaml", "pubspec.lock"],
    install: ["flutter pub get"],
    build: ["flutter build web --release"],
    outputDirs: ["build/web"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", "build/web", "-l", String(port)] }),
    detectPriority: 70,
  },
  {
    id: "dart",
    name: "Dart",
    icon: "🎯",
    extensions: [".dart"],
    configFiles: ["pubspec.yaml", "pubspec.lock"],
    install: ["dart pub get"],
    build: ["dart compile exe bin/server.dart"],
    outputDirs: ["bin"],
    startCommand: () => ({ cmd: "dart", args: ["bin/server.exe"] }),
    detectPriority: 50,
  },
  {
    id: "dart-shelf",
    name: "Dart (Shelf)",
    icon: "📦",
    extensions: [".dart"],
    configFiles: ["pubspec.yaml"],
    install: ["dart pub get"],
    build: [],
    outputDirs: ["."],
    startCommand: () => ({ cmd: "dart", args: ["run", "bin/server.dart"] }),
    detectPriority: 51,
  },

  // ═══════════════════════════════════════════════════════════════
  // Swift
  // ═══════════════════════════════════════════════════════════════
  {
    id: "vapor",
    name: "Vapor (Swift)",
    icon: "💧",
    extensions: [".swift"],
    configFiles: ["Package.swift", "Package.resolved"],
    install: ["swift package resolve"],
    build: ["swift build -c release"],
    outputDirs: [".build/release"],
    startCommand: () => ({ cmd: ".build/release/server", args: [] }),
    env: { PORT: "3000", ENV: "production" },
    detectPriority: 65,
  },
  {
    id: "swift",
    name: "Swift",
    icon: "🐦",
    extensions: [".swift"],
    configFiles: ["Package.swift"],
    install: ["swift package resolve"],
    build: ["swift build -c release"],
    outputDirs: [".build/release"],
    startCommand: () => ({ cmd: ".build/release/server", args: [] }),
    env: { PORT: "3000" },
    detectPriority: 50,
  },

  // ═══════════════════════════════════════════════════════════════
  // C / C++
  // ═══════════════════════════════════════════════════════════════
  {
    id: "cpp",
    name: "C++",
    icon: "⚙️",
    extensions: [".cpp", ".cc", ".cxx", ".hpp", ".h"],
    configFiles: ["CMakeLists.txt", "Makefile", "meson.build"],
    install: [],
    build: ["cmake -B build . && cmake --build build", "or", "make"],
    outputDirs: ["build", "bin"],
    startCommand: () => ({ cmd: "./build/server", args: [] }),
    env: { PORT: "3000" },
    detectPriority: 50,
  },
  {
    id: "c",
    name: "C",
    icon: "🔧",
    extensions: [".c", ".h"],
    configFiles: ["CMakeLists.txt", "Makefile", "meson.build"],
    install: [],
    build: ["make", "or", "cmake -B build . && cmake --build build"],
    outputDirs: ["build", "bin"],
    startCommand: () => ({ cmd: "./build/server", args: [] }),
    env: { PORT: "3000" },
    detectPriority: 45,
  },
  {
    id: "crow",
    name: "C++ (Crow)",
    icon: "🐦",
    extensions: [".cpp", ".hpp"],
    configFiles: ["CMakeLists.txt"],
    install: [],
    build: ["cmake -B build . && cmake --build build"],
    outputDirs: ["build"],
    startCommand: () => ({ cmd: "./build/server", args: [] }),
    env: { PORT: "3000" },
    detectPriority: 46,
  },
  {
    id: "drogon",
    name: "C++ (Drogon)",
    icon: "🐉",
    extensions: [".cpp", ".cc", ".h"],
    configFiles: ["CMakeLists.txt", "config.json"],
    install: [],
    build: ["cmake -B build . && cmake --build build"],
    outputDirs: ["build"],
    startCommand: () => ({ cmd: "./build/server", args: [] }),
    env: { PORT: "3000" },
    detectPriority: 47,
  },

  // ═══════════════════════════════════════════════════════════════
  // Lua
  // ═══════════════════════════════════════════════════════════════
  {
    id: "openresty",
    name: "OpenResty (Lua)",
    icon: "🌙",
    extensions: [".lua", ".conf"],
    configFiles: ["nginx.conf", "rockspec"],
    install: ["luarocks install"],
    build: [],
    outputDirs: ["."],
    startCommand: () => ({ cmd: "openresty", args: ["-c", "nginx.conf"] }),
    env: { LUA_PATH: "./?.lua;;" },
    detectPriority: 40,
  },
  {
    id: "lapis",
    name: "Lapis (Lua)",
    icon: "🌊",
    extensions: [".lua"],
    configFiles: ["app.lua", "config.lua", "rockspec"],
    install: ["luarocks install"],
    build: [],
    outputDirs: ["."],
    startCommand: () => ({ cmd: "lapis", args: ["server"] }),
    detectPriority: 41,
  },

  // ═══════════════════════════════════════════════════════════════
  // Haskell
  // ═══════════════════════════════════════════════════════════════
  {
    id: "haskell",
    name: "Haskell",
    icon: "λ",
    extensions: [".hs", ".cabal"],
    configFiles: ["*.cabal", "stack.yaml", "cabal.project"],
    install: ["cabal update", "or", "stack setup"],
    build: ["cabal build all", "or", "stack build"],
    outputDirs: ["dist-newstyle", ".stack-work"],
    startCommand: () => ({ cmd: "cabal", args: ["run", "server"] }),
    env: { GHCRTS: "+RTS -M512M -RTS" },
    detectPriority: 55,
  },
  {
    id: "servant",
    name: "Haskell (Servant)",
    icon: "🛐",
    extensions: [".hs", ".cabal"],
    configFiles: ["*.cabal", "stack.yaml"],
    install: ["cabal update"],
    build: ["cabal build"],
    outputDirs: ["dist-newstyle"],
    startCommand: () => ({ cmd: "cabal", args: ["run", "server"] }),
    detectPriority: 56,
  },
  {
    id: "yesod",
    name: "Haskell (Yesod)",
    icon: "🏗️",
    extensions: [".hs", ".cabal", ".hamlet", ".julius"],
    configFiles: ["*.cabal", "config/settings.yml"],
    install: ["cabal update"],
    build: ["cabal build"],
    outputDirs: ["dist-newstyle"],
    startCommand: () => ({ cmd: "cabal", args: ["run", "server"] }),
    detectPriority: 57,
  },

  // ═══════════════════════════════════════════════════════════════
  // R
  // ═══════════════════════════════════════════════════════════════
  {
    id: "shiny",
    name: "R (Shiny)",
    icon: "📊",
    extensions: [".r", ".R", ".rmd"],
    configFiles: ["app.R", "server.R", "ui.R", "DESCRIPTION"],
    install: ["Rscript -e 'install.packages(\"renv\")' && Rscript -e 'renv::restore()'"],
    build: [],
    outputDirs: ["."],
    startCommand: () => ({ cmd: "Rscript", args: ["app.R"] }),
    env: { SHINY_HOST: "0.0.0.0", SHINY_PORT: "3000" },
    detectPriority: 55,
  },
  {
    id: "plumber",
    name: "R (Plumber)",
    icon: "🔧",
    extensions: [".r", ".R", ".plumber"],
    configFiles: ["plumber.R", "Dockerfile"],
    install: ["Rscript -e 'install.packages(\"renv\")' && Rscript -e 'renv::restore()'"],
    build: [],
    outputDirs: ["."],
    startCommand: () => ({ cmd: "Rscript", args: ["-e", "plumber::plumb('plumber.R')$run(host='0.0.0.0', port=3000)"] }),
    detectPriority: 50,
  },

  // ═══════════════════════════════════════════════════════════════
  // Perl
  // ═══════════════════════════════════════════════════════════════
  {
    id: "perl-dancer",
    name: "Perl (Dancer2)",
    icon: "💃",
    extensions: [".pl", ".pm"],
    configFiles: ["cpanfile", "Makefile.PL"],
    install: ["cpanm --installdeps ."],
    build: [],
    outputDirs: ["."],
    startCommand: () => ({ cmd: "perl", args: ["bin/app.pl", "--port=3000"] }),
    detectPriority: 35,
  },
  {
    id: "mojolicious",
    name: "Perl (Mojolicious)",
    icon: "🦊",
    extensions: [".pl", ".pm", ".ep"],
    configFiles: ["cpanfile", "script/app"],
    install: ["cpanm --installdeps ."],
    build: [],
    outputDirs: ["."],
    startCommand: () => ({ cmd: "perl", args: ["script/app", "daemon", "-l", "http://*:3000"] }),
    detectPriority: 36,
  },

  // ═══════════════════════════════════════════════════════════════
  // Zig
  // ═══════════════════════════════════════════════════════════════
  {
    id: "zig",
    name: "Zig",
    icon: "⚡",
    extensions: [".zig"],
    configFiles: ["build.zig", "build.zig.zon"],
    install: [],
    build: ["zig build -Doptimize=ReleaseFast"],
    outputDirs: ["zig-out"],
    startCommand: () => ({ cmd: "./zig-out/bin/server", args: [] }),
    env: { PORT: "3000" },
    detectPriority: 50,
  },

  // ═══════════════════════════════════════════════════════════════
  // OCaml
  // ═══════════════════════════════════════════════════════════════
  {
    id: "ocaml",
    name: "OCaml",
    icon: "🐫",
    extensions: [".ml", ".mli"],
    configFiles: ["dune-project", "dune", "*.opam"],
    install: ["opam install . --deps-only"],
    build: ["dune build"],
    outputDirs: ["_build/default"],
    startCommand: () => ({ cmd: "dune", args: ["exec", "server"] }),
    detectPriority: 45,
  },

  // ═══════════════════════════════════════════════════════════════
  // Erlang
  // ═══════════════════════════════════════════════════════════════
  {
    id: "erlang",
    name: "Erlang",
    icon: "📱",
    extensions: [".erl", ".hrl"],
    configFiles: ["rebar.config", "rebar.lock", "Emakefile"],
    install: ["rebar3 get-deps"],
    build: ["rebar3 compile"],
    outputDirs: ["_build/default/lib"],
    startCommand: () => ({ cmd: "rebar3", args: ["shell"] }),
    detectPriority: 45,
  },

  // ═══════════════════════════════════════════════════════════════
  // Static Sites / HTML / CSS
  // ═══════════════════════════════════════════════════════════════
  {
    id: "html",
    name: "Static HTML",
    icon: "📄",
    extensions: [".html", ".htm", ".css", ".js"],
    configFiles: [],
    install: [],
    build: [],
    outputDirs: ["."],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", ".", "-l", String(port)] }),
    detectPriority: 10,
  },
  {
    id: "netlify",
    name: "Netlify-style",
    icon: "🌐",
    extensions: [".html", ".css", ".js", ".json"],
    configFiles: ["netlify.toml", "vercel.json", "_redirects", "_headers"],
    install: [],
    build: [],
    outputDirs: ["dist", "build", "public", "site"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", ".", "-l", String(port)] }),
    detectPriority: 15,
  },

  // ═══════════════════════════════════════════════════════════════
  // WebAssembly
  // ═══════════════════════════════════════════════════════════════
  {
    id: "wasm",
    name: "WebAssembly",
    icon: "🔮",
    extensions: [".wasm", ".wat", ".rs", ".cpp", ".go"],
    configFiles: ["Cargo.toml", "CMakeLists.txt", "go.mod"],
    install: [],
    build: ["cargo build --target wasm32-unknown-emscripten", "or", "emcmake cmake . && make"],
    outputDirs: ["target/wasm32", "."],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", ".", "-l", String(port)] }),
    detectPriority: 30,
  },

  // ═══════════════════════════════════════════════════════════════
  // Mobile / Cross-platform
  // ═══════════════════════════════════════════════════════════════
  {
    id: "react-native",
    name: "React Native (Web)",
    icon: "📱",
    extensions: [".tsx", ".ts", ".jsx", ".js"],
    configFiles: ["react-native.config.js", "metro.config.js"],
    install: ["npm install"],
    build: ["npx react-native bundle --platform web --dev false --entry-file index.js --bundle-output dist/bundle.js"],
    outputDirs: ["dist"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", "dist", "-l", String(port)] }),
    detectPriority: 50,
  },
  {
    id: "capacitor",
    name: "Capacitor",
    icon: "⚡",
    extensions: [".ts", ".js", ".java", ".swift"],
    configFiles: ["capacitor.config.ts", "capacitor.config.json"],
    install: ["npm install"],
    build: ["npx cap sync web"],
    outputDirs: ["www"],
    startCommand: (port) => ({ cmd: "npx", args: ["serve", "www", "-l", String(port)] }),
    detectPriority: 45,
  },
];

export function detectLanguage(files: string[]): LanguageProfile | null {
  const scored = LANGUAGES.map((lang) => {
    let score = 0;

    // Config file match (highest priority)
    for (const config of lang.configFiles) {
      if (files.some((f) => f === config || f.endsWith("/" + config))) {
        score += 100;
        break;
      }
    }

    // Extension match
    const extCount = files.filter((f) =>
      lang.extensions.some((ext) => f.endsWith(ext))
    ).length;
    score += extCount * 10;

    // Apply priority boost
    score += lang.detectPriority || 0;

    return { lang, score };
  });

  scored.sort((a, b) => b.score - a.score);

  const best = scored[0];
  if (best && best.score > 0) {
    return best.lang;
  }

  return null;
}

export function getLanguageById(id: string): LanguageProfile | undefined {
  return LANGUAGES.find((l) => l.id === id);
}
