github:
  - your-github-username

patreon: your-patreon-username
open_collective: your-open-collective-slug
ko_fi: your-kofi-username
tidelift: npm/your-package-name
community_bridge: your-community-bridge-project
liberapay: your-liberapay-username
issuehunt: your-issuehunt-username
polar: your-polar-username
buy_me_a_coffee: your-buymeacoffee-username
thanks_dev: u/gh/octocat

custom:
  - https://yourdomain.com/donate
  - https://yourdomain.com/sponsor
